/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.LibrarianRole;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class LibrarianRoleGUI extends javax.swing.JFrame implements Point,Role{

    /**
     * Creates new form LibrarianRole
     */
    public LibrarianRoleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewBook = new javax.swing.JButton();
        BorrowBook = new javax.swing.JButton();
        ViewBorrowedBooks = new javax.swing.JButton();
        AddBook = new javax.swing.JButton();
        ReturnBook = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Librarian Role");

        ViewBook.setBackground(new java.awt.Color(0, 0, 0));
        ViewBook.setForeground(new java.awt.Color(255, 255, 255));
        ViewBook.setText("View Books");
        ViewBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookActionPerformed(evt);
            }
        });

        BorrowBook.setBackground(new java.awt.Color(0, 0, 0));
        BorrowBook.setForeground(new java.awt.Color(255, 255, 255));
        BorrowBook.setText("Borrow Book");
        BorrowBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBookActionPerformed(evt);
            }
        });

        ViewBorrowedBooks.setBackground(new java.awt.Color(0, 0, 0));
        ViewBorrowedBooks.setForeground(new java.awt.Color(255, 255, 255));
        ViewBorrowedBooks.setText("View Borrowed Books");
        ViewBorrowedBooks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewBorrowedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBorrowedBooksActionPerformed(evt);
            }
        });

        AddBook.setBackground(new java.awt.Color(0, 0, 0));
        AddBook.setForeground(new java.awt.Color(255, 255, 255));
        AddBook.setText("Add Book");
        AddBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        ReturnBook.setBackground(new java.awt.Color(0, 0, 0));
        ReturnBook.setForeground(new java.awt.Color(255, 255, 255));
        ReturnBook.setText("Return Book");
        ReturnBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewBook, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(BorrowBook, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(ViewBorrowedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(ReturnBook, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewBorrowedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        int n = librarian.getListOfBooks().length;
        String[][] data = new String[n][5];
        String[] headers = new String[]{"Book ID", "Title", "Author Name", "Publisher Name", "No. Of Copies"};
        for(int i = 0; i < n; i ++)
        {
            data[i] = librarian.getListOfBooks()[i].lineRepresentation().split(",");
        }
        books = new View(headers,data,"View Books");
        books.setPreviousPoint(this);
        books.setVisible(true);
    }//GEN-LAST:event_ViewBookActionPerformed

    private void BorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BorrowBook x = new BorrowBook();
        x.setPreviousPoint(this);
        x.setVisible(true);
    }//GEN-LAST:event_BorrowBookActionPerformed

    private void ViewBorrowedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBorrowedBooksActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //ViewBorrowedBooks x = new ViewBorrowedBooks(new String[] {"Student Id", "Book Id", "Borrow Date"});
        int n = librarian.getListOfBorrowingOperations().length;
        String[][] data = new String[n][3];
        String[] headers = new String[] {"Student Id", "Book Id", "Borrow Date"};
        for(int i = 0; i < n; i ++)
        {
            data[i] = librarian.getListOfBorrowingOperations()[i].lineRepresentation().split(",");
        }
        studentBooks = new View(headers,data,"View Borrowed Books");
        studentBooks.setPreviousPoint(this);
        studentBooks.setVisible(true);
    }//GEN-LAST:event_ViewBorrowedBooksActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Add x = new Add("Add Book");
        x.setPreviousPoint(this);
        x.setVisible(true);
    }//GEN-LAST:event_AddBookActionPerformed

    private void ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ReturnBook x = new ReturnBook();
        x.setPreviousPoint(this);
        x.setVisible(true);
    }//GEN-LAST:event_ReturnBookActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.librarian.logout();
        this.setVisible(false);
        ((JFrame)(getPreviousPoint().getPreviousPoint())).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianRoleGUI().setVisible(true);
            }
        });
    }
public void setPreviousPoint(Point point)
{
    this.prevPoint = point;
}
public Point getPreviousPoint()
{
    return this.prevPoint;
}
private Point prevPoint;
LibrarianRole librarian = new LibrarianRole();
View books;
View studentBooks;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton BorrowBook;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ReturnBook;
    private javax.swing.JButton ViewBook;
    private javax.swing.JButton ViewBorrowedBooks;
    // End of variables declaration//GEN-END:variables
}
